#!/bin/bash

if  !command -v go &> /dev/null
then
    echo "go cli could not be found. Please refer to https://go.dev/doc/install to install golang"
    exit
fi

# Install golang dependencies
go install github.com/cweill/gotests/gotests@latest
go install github.com/davidrjenni/reftools/cmd/fillstruct@latest
